# Workflow Configuration
# Define workflow statuses and filtering rules

# Borrower-facing workflow statuses
# These statuses are returned when querying workflows for borrower actions
borrower_workflows:
  statuses:
    - AWAITING_APPROVAL  # Workflows awaiting borrower approval
    - APPROVED           # Workflows that have been approved by borrower

  # Optional: Add more borrower workflow config here
  default_limit: 10

# Advisor-facing workflow statuses (for future use)
advisor_workflows:
  statuses:
    - AWAITING_APPROVAL
    - APPROVED
    - IN_PROGRESS
    - PENDING_EXECUTION

  default_limit: 50

# All possible workflow statuses in the system (for reference)
all_statuses:
  - CREATED
  - AWAITING_APPROVAL
  - APPROVED
  - REJECTED
  - IN_PROGRESS
  - PENDING_EXECUTION
  - EXECUTED
  - FAILED
  - CANCELLED
