"""
Predictive Knowledge Extractor - Transform insights into institutional learning.

Takes insights from pipeline stages and transforms them into patterns, predictions,
and wisdom that can be stored in the knowledge graph for future learning.
"""
from typing import Dict, Any, List, Optional
import logging
from datetime import datetime, timedelta
import uuid

from .knowledge_types import Pattern, Prediction, Wisdom, MetaLearning, PredictiveInsight
try:
    from .predictive_graph_manager import PredictiveGraphManager
    GRAPH_MANAGER_AVAILABLE = True
except ImportError:
    GRAPH_MANAGER_AVAILABLE = False
try:
    from ..events import publish_event, Event, EventType
    EVENTS_AVAILABLE = True
except ImportError:
    EVENTS_AVAILABLE = False

logger = logging.getLogger(__name__)


class PredictiveKnowledgeExtractor:
    """
    Extracts predictive knowledge from pipeline insights.

    Transforms LLM-generated insights into structured knowledge that enables
    the system to learn, predict, and intervene proactively.
    """

    def __init__(self, db_path: Optional[str] = None):
        if db_path is None:
            from ..config.database_config import get_knowledge_graph_database_path
            db_path = get_knowledge_graph_database_path()
        if not GRAPH_MANAGER_AVAILABLE:
            raise RuntimeError("PredictiveGraphManager not available - cannot proceed without proper storage")
        self.graph_manager = PredictiveGraphManager(db_path)

    async def extract_knowledge(self, insight: PredictiveInsight, context: Dict[str, Any]) -> None:
        """
        Extract predictive knowledge from a pipeline insight.

        Args:
            insight: The insight generated by a pipeline stage
            context: Additional context about the source of the insight

        Raises:
            Exception: When knowledge extraction fails (NO FALLBACK)
        """
        if insight.priority == 'skip':
            logger.info(f"🚫 Skipping knowledge extraction based on priority")
            return

        logger.info(f"🧠 Extracting {insight.insight_type} knowledge from {insight.source_stage}")
        logger.info(f"   Priority: {insight.priority}, Learning: {insight.learning_value}")
        logger.info(f"   Reasoning: {insight.reasoning}")

        try:
            if insight.insight_type == 'pattern':
                await self._extract_pattern(insight, context)
            elif insight.insight_type == 'prediction':
                await self._extract_prediction(insight, context)
            elif insight.insight_type == 'wisdom':
                await self._extract_wisdom(insight, context)
            elif insight.insight_type == 'meta_learning':
                await self._extract_meta_learning(insight, context)
            else:
                logger.warning(f"Unknown insight type: {insight.insight_type}")

            # Publish knowledge extraction event
            await self._publish_knowledge_event(insight, context)

            logger.info(f"✅ Successfully extracted {insight.insight_type} knowledge")

        except Exception as e:
            # NO FALLBACK: Fail fast on knowledge extraction errors
            logger.error(f"Failed to extract knowledge from insight: {e}")
            raise RuntimeError(f"Knowledge extraction failed: {str(e)}")

    async def _extract_pattern(self, insight: PredictiveInsight, context: Dict[str, Any]) -> None:
        """Extract a behavioral or operational pattern."""
        content = insight.content

        pattern = Pattern(
            pattern_id=f"PATTERN_{uuid.uuid4().hex[:8]}",
            pattern_type=content.get('pattern_type', 'behavioral'),
            title=content.get('title', f"Pattern from {insight.source_stage}"),
            description=content.get('description', 'Pattern discovered during pipeline processing'),
            conditions=content.get('conditions', {}),
            outcomes=content.get('outcomes', {}),
            confidence=content.get('confidence', 0.7),
            occurrences=1,  # First observation
            success_rate=content.get('success_rate', 0.5),
            last_observed=insight.timestamp,
            source_pipeline=insight.source_stage
        )

        # NO FALLBACK: Store pattern or fail
        await self.graph_manager.store_pattern(pattern)
        logger.info(f"📊 Stored pattern: {pattern.title}")

    async def _extract_prediction(self, insight: PredictiveInsight, context: Dict[str, Any]) -> None:
        """Extract a predictive insight about future events."""
        content = insight.content

        prediction = Prediction(
            prediction_id=f"PRED_{uuid.uuid4().hex[:8]}",
            prediction_type=content.get('prediction_type', 'risk_assessment'),
            target_entity=content.get('target_entity', 'Customer'),
            target_entity_id=context.get('customer_id', 'UNKNOWN'),
            predicted_event=content.get('predicted_event', 'Unknown event'),
            probability=content.get('probability', 0.5),
            confidence=content.get('confidence', 0.7),
            time_horizon=content.get('time_horizon', 'short_term'),
            supporting_patterns=content.get('supporting_patterns', []),
            evidence_strength=content.get('evidence_strength', 0.5),
            created_at=insight.timestamp,
            expires_at=insight.timestamp + timedelta(days=30)  # Default 30-day expiration
        )

        # NO FALLBACK: Store prediction or fail
        await self.graph_manager.store_prediction(prediction)
        logger.info(f"🔮 Stored prediction: {prediction.predicted_event}")

    async def _extract_wisdom(self, insight: PredictiveInsight, context: Dict[str, Any]) -> None:
        """Extract strategic wisdom and institutional knowledge."""
        content = insight.content

        wisdom = Wisdom(
            wisdom_id=f"WISDOM_{uuid.uuid4().hex[:8]}",
            wisdom_type=content.get('wisdom_type', 'strategic_insight'),
            domain=content.get('domain', 'customer_operations'),
            insight=content.get('insight', 'Strategic insight discovered'),
            applications=content.get('applications', []),
            success_indicators=content.get('success_indicators', []),
            derived_from_patterns=content.get('derived_from_patterns', []),
            evidence_base=content.get('evidence_base', {}),
            confidence_level=content.get('confidence_level', 0.7),
            discovered_at=insight.timestamp,
            times_applied=0,
            application_success_rate=0.0
        )

        # NO FALLBACK: Store wisdom or fail
        await self.graph_manager.store_wisdom(wisdom)
        logger.info(f"🧠 Stored wisdom: {wisdom.insight[:50]}...")

    async def _extract_meta_learning(self, insight: PredictiveInsight, context: Dict[str, Any]) -> None:
        """Extract meta-learning about the system's learning process."""
        content = insight.content

        meta_learning = MetaLearning(
            meta_id=f"META_{uuid.uuid4().hex[:8]}",
            meta_type=content.get('meta_type', 'system_improvement'),
            learning_insight=content.get('learning_insight', 'System learning insight'),
            improvement_opportunity=content.get('improvement_opportunity', 'Optimization opportunity'),
            optimization_suggestion=content.get('optimization_suggestion', 'Suggested improvement'),
            accuracy_metrics=content.get('accuracy_metrics', {}),
            learning_velocity=content.get('learning_velocity', 0.5),
            knowledge_gaps=content.get('knowledge_gaps', []),
            observed_at=insight.timestamp,
            system_version="v2.0"
        )

        # NO FALLBACK: Store meta-learning or fail
        await self.graph_manager.store_meta_learning(meta_learning)
        logger.info(f"🔄 Stored meta-learning: {meta_learning.learning_insight[:50]}...")

    async def _publish_knowledge_event(self, insight: PredictiveInsight, context: Dict[str, Any]) -> None:
        """Publish an event about knowledge extraction."""
        event_data = {
            'event_type': f'KNOWLEDGE_EXTRACTED_{insight.insight_type.upper()}',
            'timestamp': datetime.utcnow().isoformat(),
            'source': 'predictive_knowledge_extractor',
            'insight_type': insight.insight_type,
            'source_stage': insight.source_stage,
            'priority': insight.priority,
            'learning_value': insight.learning_value,
            'context': context,
            'reasoning': insight.reasoning
        }

        if not EVENTS_AVAILABLE:
            raise RuntimeError("Event system not available - cannot proceed without event publishing")

        # NO FALLBACK: Publish event or fail
        event = Event(
            event_type=EventType.KNOWLEDGE_EXTRACTED,
            event_id=f"knowledge_{uuid.uuid4().hex[:8]}",
            timestamp=datetime.utcnow(),
            source_service="predictive_knowledge_extractor",
            payload=event_data
        )
        publish_event(event)

    async def get_relevant_patterns(self, context: Dict[str, Any]) -> List[Pattern]:
        """Get patterns relevant to the current context."""
        # NO FALLBACK: Query patterns or fail
        return await self.graph_manager.get_patterns_by_context(context)

    async def get_predictions_for_entity(self, entity_type: str, entity_id: str) -> List[Prediction]:
        """Get active predictions for a specific entity."""
        # NO FALLBACK: Query predictions or fail
        return await self.graph_manager.get_predictions_for_entity(entity_type, entity_id)

    async def validate_prediction(self, prediction_id: str, outcome: bool) -> None:
        """Validate a prediction with actual outcome."""
        await self.graph_manager.validate_prediction(prediction_id, outcome)
        logger.info(f"✅ Validated prediction {prediction_id}: {'SUCCESS' if outcome else 'FAILED'}")

    async def update_pattern_evidence(self, pattern_id: str, new_observation: Dict[str, Any]) -> None:
        """Update a pattern with new evidence."""
        await self.graph_manager.update_pattern_evidence(pattern_id, new_observation)
        logger.info(f"📊 Updated pattern {pattern_id} with new evidence")


# Global instance
_knowledge_extractor = None

def get_predictive_knowledge_extractor() -> PredictiveKnowledgeExtractor:
    """Get the global predictive knowledge extractor instance."""
    global _knowledge_extractor
    if _knowledge_extractor is None:
        # NO FALLBACK: Fail fast if dependencies not available
        try:
            _knowledge_extractor = PredictiveKnowledgeExtractor()
        except RuntimeError as e:
            logger.error(f"Failed to initialize PredictiveKnowledgeExtractor: {e}")
            raise RuntimeError(f"Cannot proceed without predictive knowledge system: {e}")
    return _knowledge_extractor